name: Peter R. Barnett
favicon: null
layout_spectrum: 0.75022
typography_spectrum: 0.9873838888015598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#58a4d8'
    - '#000000'
    - '#3679a7'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.8995831615757197
  rhythmicContrast: 0.13668359885923564
purpose: []
